#
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

name: DevLake Build and Push to ECR
run-name: DevLake build and push to ECR by @${{ github.actor }}

on:
  workflow_dispatch:
  push:
    branches:
      - master
      - andy/dx-85

permissions:
  id-token: write # Required for JWT
  contents: read # Required for checkout

env:
  LATEST_TAG: v1.0.2-beta4
  COMMIT_TAG: ${{ github.sha }}
  AWS_REGION: us-east-1
  IAM_ROLE_ARN: arn:aws:iam::130726505375:role/github-actions-ecr
  ECR: 130726505375.dkr.ecr.us-east-1.amazonaws.com
  IMAGE_NAME_SERVER: devlake-server
  IMAGE_NAME_CONFIG_UI: devlake-config-ui

jobs:
  build-and-push-server:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@83b7061638ee4956cf7545a6f7efe594e5ad0247 #v3.5.1 

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@e1e17a757e536f70e52b5a12b2e8d1d1c60e04ef # v2.0.0
        with:
          role-to-assume: ${{ env.IAM_ROLE_ARN }}
          role-session-name: github-action-devlake-server-build
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          registry: ${{ env.ECR }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@4b4e9c3e2d4531116a6f8ba8e71fc6e2cb6e6c8c

      - name: Build and push container image
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: ./backend
          push: true
          file: ./backend/Dockerfile
          tags: |
            ${{ env.ECR }}/${{ env.IMAGE_NAME_SERVER }}:${{ env.LATEST_TAG }}
            ${{ env.ECR }}/${{ env.IMAGE_NAME_SERVER }}:${{ env.COMMIT_TAG }}
          platforms: linux/amd64,linux/arm64
          build-args: |
            TAG=${{ github.ref_name }}
            SHA=${{ github.sha }}

  build-and-push-config-ui:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@83b7061638ee4956cf7545a6f7efe594e5ad0247 #v3.5.1 

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@e1e17a757e536f70e52b5a12b2e8d1d1c60e04ef # v2.0.0
        with:
          role-to-assume: ${{ env.IAM_ROLE_ARN }}
          role-session-name: github-action-devlake-config-ui-build
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          registry: ${{ env.ECR }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@4b4e9c3e2d4531116a6f8ba8e71fc6e2cb6e6c8c

      - name: Build and push container image
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: ./config-ui
          push: true
          file: ./config-ui/Dockerfile
          tags: |
            ${{ env.ECR }}/${{ env.IMAGE_NAME_CONFIG_UI }}:${{ env.LATEST_TAG }}
            ${{ env.ECR }}/${{ env.IMAGE_NAME_CONFIG_UI }}:${{ env.COMMIT_TAG }}
          platforms: linux/amd64,linux/arm64
          build-args: |
            TAG=${{ github.ref_name }}
            SHA=${{ github.sha }}
